### ISSUE TITLE
CSSgram doesn't play well with CSS transformations

### ISSUE THREAD

**Issue by thelamborghinistory** [una/CSSgram#167] opened 2016-07-02 11:36 UTC
If you put a filter on something like this https://desandro.github.io/3dtransforms/docs/card-flip.html the whole thing will pretty much just break (using chrome). Not sure if it's even possible to fix that on CSS level though.

PS.: I will do a jsfiddle later once I find a few free minutes.

**Comment by una** [comment] 2016-07-06 16:51
Hmm intersting! Let me know if you've created that fiddle -- @desandro do you know what might cause this?

**Comment by desandro** [comment] 2016-07-06 19:27
Sounds like a compositing issue with the browser. If you have a **reduced test case** demonstrating that issue, we may be able to whittle it down to which property is causing the issue, then take it up with Chrome Bugs.

**Comment by thelamborghinistory** [comment] 2016-07-07 02:04
Here is a jsfiddle: https://jsfiddle.net/thelamborghinistory/1mLxk41s/ (sorry it took so long, I forgot about that I wanted to do that!).

If you flip the card without a filter applied, it works like a charm. If you add a filter to it you will start seeing a flickering while the card flips around, which is the issue I have found with it. Another thing I noticed is, that it's only flickering you use the `overflow: hidden;` stuff as well to get the rounded corners (comment it out and it works pretty fantastic). I really have doubts about this being fixable with CSS.

**Comment by goldins** [comment] 2016-09-30 14:42
The flickering seems like a `z-index` issue. Try adding `z-index` values so they're not on the same plane. Also, try using 3d transformations as they usually perform better due to hardware acceleration.

**Comment by DeMuu** [comment] 2016-10-04 18:35
Hi,

I just played around a bit with this issue and discovered that changing the position attribute actually fixes the flickering. 😄 

Changing the `#card figure` element's `position: absolute` to `position: fixed` is all it takes. Testing the result in the fiddle didn't bring up any other issues caused by this change but if I missed anything here please tell me 👍 

Here's the forked fiddle: https://jsfiddle.net/DeMuu/zv8cjrc2/2/

**Comment by una** [comment] 2016-10-04 20:29
Interesting... I wonder if this is a browser bug. Did you test on any other systems?

**Comment by DeMuu** [comment] 2016-10-05 07:29
I tested it with Firefox and Safari as well (macOS). Firefox seems to have a rendering issue cause there's a bit of flickering even without any filters. Safari has a problem with an iframe property jsFiddle is using so it doesn't work.

**Comment by una** [comment] 2017-02-07 03:22
Closing since this seems to be a browser-level issue

**Closed by una** 2017-02-07 03:22 UTC
